title:              Personal blog 
tagline:            by SanSyun
description:        Content-focused template for a blog hosted on GitHub Pages.
url:                http://sansyun.github.io

author:
  name:             San Syun
  url:              https://twitter.com/YourName
  email:            schen0303@163.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
