title:              San Syun 
tagline:            Personal blog
description:        Record of the development process and thoughts.
url:                http://sansyun.github.io

author:
  name:             San Syun
  url:              http://sansyun.github.io
  email:            schen0303@163.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post

# 添加分类支持
collections:
  categories:
    output: true

# 使用 Minimal Mistakes 的远程主题（固定一个稳定版本）
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-include-cache
